### ISSUE TITLE
Couldn't push the changes

### ISSUE THREAD

**Issue by JohaanMannanal** [ArjunSharda/Best-404-Page-1-2022-Hackathon#10]
ubuntu@foo:~/src/Best-404-Page-1-2022-Hackathon$ git push --set-upstream origin embros-team
Username for 'https://github.com': JohaanMannanal
Password for 'https://JohaanMannanal@github.com':
remote: Permission to ArjunSharda/Best-404-Page-1-2022-Hackathon.git denied to JohaanMannanal.
fatal: unable to access 'https://github.com/ArjunSharda/Best-404-Page-1-2022-Hackathon.git/': The requested URL returned error: 403

**Comment by JohaanMannanal** [comment]
![image](https://user-images.githubusercontent.com/106918089/178928382-a6b74b29-1206-40cc-b8d1-29a32a940952.png)

**Comment by JohaanMannanal** [comment]
@ArjunSharda Due to above errors, I am not able to push the changes.

**Comment by ArjunSharda** [comment]
> @ArjunSharda Due to above errors, I am not able to push the changes.

Yes, you will need to make a fork and from your branch in the fork (embros-team) you will need to add your code in the directory and make a PR for the changes to the repository and it would be merged.

**Comment by JohaanMannanal** [comment]
Thank you
